name: Deploy Adonis App to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: SSH and deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no paperspace@${{ secrets.SERVER_IP }} << 'EOF'
            # Load NVM properly in non-interactive SSH shell
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20.19.2

            # Navigate to project directory
            cd ~/JoeyRavenTest

            # Install dependencies
            npm ci

            # Build project for production or development
            npm run build -- --env=production

            # Start or restart PM2
            cd build
            pm2 restart JoeyRavenTest || pm2 start bin/server.js --name JoeyRavenTest
          EOF
