name: Deploy Adonis App to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: SSH and deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no paperspace@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/JoeyRavenTest
            git pull origin main
            npm ci
            npm run build
            pm2 restart JoeyRavenTest || pm2 start build/bin/server.js --name JoeyRavenTest
          EOF

