name: Deploy AdonisJS App to Paperspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Paperspace server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            echo "Starting deployment on server..."

            cd /home/paperspace/JoeyRavenTest
            git pull origin main
            npm ci
            node ace build
            pm2 restart adonis-web || pm2 start build/server.js --name adonis-web

            echo "Deployment complete."
          EOF
